# Generated by Django 4.0.2 on 2022-02-17 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_follows'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flux', '0003_ticketcontributor_ticket_contributors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution', models.CharField(blank=True, max_length=255)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='contributors',
            field=models.ManyToManyField(related_name='reviewcontributions', through='flux.ReviewContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contributors',
            field=models.ManyToManyField(related_name='ticketcontributions', through='flux.TicketContributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('user', 'followed_user')},
        ),
        migrations.AddField(
            model_name='reviewcontributor',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flux.review'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewcontributor',
            unique_together={('contributor', 'review')},
        ),
    ]
